<?php
  if (!defined('WPINC')) { die; }

  if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
  	'key' => 'group_59f5140d56a78',
  	'title' => 'ExCon - Group - Module',
  	'fields' => array(
  		array(
  			'key' => 'field_59f514257fc7a',
  			'label' => 'Exonym Settings Group',
  			'name' => 'exonym_settings_group',
  			'type' => 'clone',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'clone' => array(
  				0 => 'group_59f5076d561aa',
  				1 => 'group_59f4f2fcc0e59',
  				2 => 'group_59f4fc19d26a0',
  				3 => 'group_59f5113038280',
  				4 => 'group_59f51288a86d9',
  				5 => 'group_59f55977ba0e7',
  			),
  			'display' => 'seamless',
  			'layout' => 'block',
  			'prefix_label' => 0,
  			'prefix_name' => 0,
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f55977ba0e7',
  	'title' => 'ExCon - Setting - Advanced',
  	'fields' => array(
  		array(
  			'key' => 'field_59f55983ef42e',
  			'label' => 'Advanced',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f55992ef42f',
  			'label' => 'Custom ID',
  			'name' => 'custom_id',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
  		array(
  			'key' => 'field_59f559c2ef430',
  			'label' => 'Custom Classes',
  			'name' => 'custom_classes',
  			'type' => 'text',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '',
  		),
  		array(
  			'key' => 'field_59f559d5ef431',
  			'label' => 'Pre-Content HTML',
  			'name' => 'pre-content_html',
  			'type' => 'textarea',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'maxlength' => '',
  			'rows' => 4,
  			'new_lines' => '',
  		),
  		array(
  			'key' => 'field_59f559e8ef432',
  			'label' => 'Post-Content HTML',
  			'name' => 'post-content_html',
  			'type' => 'textarea',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'maxlength' => '',
  			'rows' => 4,
  			'new_lines' => '',
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f5113038280',
  	'title' => 'ExCon - Setting - Animation',
  	'fields' => array(
  		array(
  			'key' => 'field_59f5113abf609',
  			'label' => 'Animate',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f517e58e69d',
  			'label' => 'Parallax',
  			'name' => 'parallax',
  			'type' => 'button_group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'choices' => array(
  				'none' => 'None',
  				'subtle' => 'Subtle',
  				'normal' => 'Normal',
  				'extreme' => 'Extreme',
  			),
  			'allow_null' => 0,
  			'default_value' => 'none',
  			'layout' => 'horizontal',
  			'return_format' => 'value',
  		),
  		array(
  			'key' => 'field_59f5115abf60a',
  			'label' => 'Animate',
  			'name' => 'animate',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'table',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f5117bbf60b',
  					'label' => 'Enter',
  					'name' => 'enter',
  					'type' => 'true_false',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'message' => 'Animate when item enters the viewport',
  					'default_value' => 1,
  					'ui' => 0,
  					'ui_on_text' => '',
  					'ui_off_text' => '',
  				),
  				array(
  					'key' => 'field_59f5119bbf60c',
  					'label' => 'Leave',
  					'name' => 'leave',
  					'type' => 'true_false',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'message' => 'Animate when item leaves the viewport',
  					'default_value' => 0,
  					'ui' => 0,
  					'ui_on_text' => '',
  					'ui_off_text' => '',
  				),
  			),
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f5076d561aa',
  	'title' => 'ExCon - Setting - CTA',
  	'fields' => array(
  		array(
  			'key' => 'field_59f50c18bb216',
  			'label' => 'CTA\'s',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f50de8e18b6',
  			'label' => 'CTA Placement',
  			'name' => 'cta_placement',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'table',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f50e00e18b7',
  					'label' => 'Position',
  					'name' => 'position',
  					'type' => 'button_group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'above' => 'Above Content',
  						'below' => 'Below Content',
  					),
  					'allow_null' => 0,
  					'default_value' => 'below',
  					'layout' => 'horizontal',
  					'return_format' => 'value',
  				),
  				array(
  					'key' => 'field_59f50e0ce18b8',
  					'label' => 'Alignment',
  					'name' => 'alignment',
  					'type' => 'button_group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'left' => 'Left',
  						'center' => 'Center',
  						'right' => 'Right',
  					),
  					'allow_null' => 0,
  					'default_value' => '',
  					'layout' => 'horizontal',
  					'return_format' => 'value',
  				),
  			),
  		),
  		array(
  			'key' => 'field_59f5079d8cfe1',
  			'label' => 'Call to Actions',
  			'name' => 'call_to_actions',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => '',
  			'min' => 0,
  			'max' => 0,
  			'layout' => 'row',
  			'button_label' => 'Add Button',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f5094c8cfe4',
  					'label' => 'Action',
  					'name' => 'action',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f5099e8cfe5',
  							'label' => 'Type',
  							'name' => 'type',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'link' => 'Link',
  								'file' => 'File',
  							),
  							'allow_null' => 0,
  							'default_value' => 'link',
  							'layout' => 'horizontal',
  							'return_format' => 'value',
  						),
  						array(
  							'key' => 'field_59f509af8cfe6',
  							'label' => 'Link',
  							'name' => 'link',
  							'type' => 'link',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_59f5099e8cfe5',
  										'operator' => '==',
  										'value' => 'link',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'return_format' => 'array',
  						),
  						array(
  							'key' => 'field_59f509e88cfe7',
  							'label' => 'File',
  							'name' => 'file',
  							'type' => 'file',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_59f5099e8cfe5',
  										'operator' => '==',
  										'value' => 'file',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'return_format' => 'array',
  							'library' => 'all',
  							'min_size' => '',
  							'max_size' => '',
  							'mime_types' => '',
  						),
  					),
  				),
  				array(
  					'key' => 'field_59f50b7743fd5',
  					'label' => 'Icon',
  					'name' => 'icon',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f50bf143fd7',
  							'label' => 'Icon',
  							'name' => 'icon',
  							'type' => 'image',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'return_format' => 'array',
  							'preview_size' => 'small',
  							'library' => 'all',
  							'min_width' => '',
  							'min_height' => '',
  							'min_size' => '',
  							'max_width' => '',
  							'max_height' => '',
  							'max_size' => '',
  							'mime_types' => '',
  						),
  						array(
  							'key' => 'field_59f50b8843fd6',
  							'label' => 'Placement',
  							'name' => 'placement',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'before' => 'Before',
  								'after' => 'After',
  							),
  							'allow_null' => 0,
  							'default_value' => 'before',
  							'layout' => 'horizontal',
  							'return_format' => 'value',
  						),
  					),
  				),
  				array(
  					'key' => 'field_59f509208cfe3',
  					'label' => 'Style',
  					'name' => 'style',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f50a4e8cfe8',
  							'label' => 'Size',
  							'name' => 'size',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '100',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'small' => 'Small',
  								'medium' => 'Medium',
  								'large' => 'Large',
  							),
  							'allow_null' => 0,
  							'default_value' => 'medium',
  							'layout' => 'horizontal',
  							'return_format' => 'value',
  						),
  						array(
  							'key' => 'field_59f50a678cfe9',
  							'label' => 'Background',
  							'name' => 'background',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'field_59f4f4c90fb26',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 1,
  							'prefix_name' => 1,
  						),
  						array(
  							'key' => 'field_59f50abb8cfea',
  							'label' => 'Text',
  							'name' => 'text',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'field_59f4f4c90fb26',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 1,
  							'prefix_name' => 1,
  						),
  					),
  				),
  				array(
  					'key' => 'field_5a09e85f3ce57',
  					'label' => 'Hide CTA',
  					'name' => 'hide_cta',
  					'type' => 'checkbox',
  					'instructions' => 'Choose which devices to hide this call to action',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'desktop' => 'Desktop',
  						'tablet' => 'Tablet',
  						'mobile' => 'Mobile',
  					),
  					'allow_custom' => 0,
  					'save_custom' => 0,
  					'default_value' => array(
  					),
  					'layout' => 'horizontal',
  					'toggle' => 0,
  					'return_format' => 'value',
  				),
  			),
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f4fc19d26a0',
  	'title' => 'ExCon - Setting - Grid',
  	'fields' => array(
  		array(
  			'key' => 'field_59f4fc6564b34',
  			'label' => 'Grid',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f4fe548a9a0',
  			'label' => 'Container',
  			'name' => 'container',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'block',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f503d4267bd',
  					'label' => 'Size',
  					'name' => 'size',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '50',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f503e1267be',
  							'label' => 'Width',
  							'name' => 'width',
  							'type' => 'range',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 12,
  							'min' => 1,
  							'max' => 12,
  							'step' => 1,
  							'prepend' => '',
  							'append' => 'columns',
  						),
  						array(
  							'key' => 'field_59f503e6267bf',
  							'label' => 'Height',
  							'name' => 'height',
  							'type' => 'group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'layout' => 'block',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_59f5040d267c0',
  									'label' => 'Amount',
  									'name' => 'amount',
  									'type' => 'number',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '50',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => 1,
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => '',
  									'min' => '',
  									'max' => '',
  									'step' => '',
  								),
  								array(
  									'key' => 'field_59f50417267c1',
  									'label' => 'Kind',
  									'name' => 'kind',
  									'type' => 'select',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '50',
  										'class' => '',
  										'id' => '',
  									),
  									'choices' => array(
  										'vh' => 'Browser Height',
  										'vw' => 'Browser Width',
  										'rem' => 'Lines of Text',
  										'px' => 'Exact Pixels',
  									),
  									'default_value' => array(
  										0 => 'px',
  									),
  									'allow_null' => 0,
  									'multiple' => 0,
  									'ui' => 0,
  									'ajax' => 0,
  									'return_format' => 'value',
  									'placeholder' => '',
  								),
  							),
  						),
  					),
  				),
  				array(
  					'key' => 'field_59f4fea38a9a2',
  					'label' => 'Padding',
  					'name' => 'padding',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '50',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f4febc8a9a3',
  							'label' => 'Top',
  							'name' => 'top',
  							'type' => 'number',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 2,
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'min' => '',
  							'max' => '',
  							'step' => '',
  						),
  						array(
  							'key' => 'field_59f4fee98a9a6',
  							'label' => 'Left',
  							'name' => 'left',
  							'type' => 'number',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 2,
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'min' => '',
  							'max' => '',
  							'step' => '',
  						),
  						array(
  							'key' => 'field_59f4feef8a9a7',
  							'label' => 'Right',
  							'name' => 'right',
  							'type' => 'number',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 2,
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'min' => '',
  							'max' => '',
  							'step' => '',
  						),
  						array(
  							'key' => 'field_59f4fed58a9a4',
  							'label' => 'Bottom',
  							'name' => 'bottom',
  							'type' => 'number',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 2,
  							'placeholder' => '',
  							'prepend' => '',
  							'append' => '',
  							'min' => '',
  							'max' => '',
  							'step' => '',
  						),
  					),
  				),
  			),
  		),
  		array(
  			'key' => 'field_59f50130267b7',
  			'label' => 'Content',
  			'name' => 'content',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'block',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f501fd267b9',
  					'label' => 'Alignment',
  					'name' => 'alignment',
  					'type' => 'group',
  					'instructions' => 'How the content aligns inside the container',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '66',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f505e33909f',
  							'label' => 'Horizontal',
  							'name' => 'horizontal',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'left' => 'Left',
  								'center' => 'Center',
  								'right' => 'Right',
  							),
  							'allow_null' => 0,
  							'default_value' => 'center',
  							'layout' => 'horizontal',
  							'return_format' => 'value',
  						),
  						array(
  							'key' => 'field_59f505fd390a0',
  							'label' => 'Vertical',
  							'name' => 'vertical',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '50',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'top' => 'Top',
  								'middle' => 'Middle',
  								'bottom' => 'Bottom',
  							),
  							'allow_null' => 0,
  							'default_value' => 'middle',
  							'layout' => 'vertical',
  							'return_format' => 'value',
  						),
  					),
  				),
  				array(
  					'key' => 'field_59f6a7fdc7bc2',
  					'label' => 'Width',
  					'name' => 'width',
  					'type' => 'group',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '34',
  						'class' => '',
  						'id' => '',
  					),
  					'layout' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f6a80fc7bc3',
  							'label' => 'Percent',
  							'name' => 'percent',
  							'type' => 'range',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 100,
  							'min' => 1,
  							'max' => 100,
  							'step' => 1,
  							'prepend' => '',
  							'append' => '%',
  						),
  						array(
  							'key' => 'field_59f6a7bb867a9',
  							'label' => 'Max Width',
  							'name' => 'max_width',
  							'type' => 'true_false',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'message' => 'Don\'t allow the width of the content exceed the main wrapper',
  							'default_value' => 0,
  							'ui' => 0,
  							'ui_on_text' => '',
  							'ui_off_text' => '',
  						),
  					),
  				),
  			),
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f51288a86d9',
  	'title' => 'ExCon - Setting - Responsive',
  	'fields' => array(
  		array(
  			'key' => 'field_59f513014e503',
  			'label' => 'Responsive',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f512c44e502',
  			'label' => 'Desktop Hide',
  			'name' => 'desktop_hide',
  			'type' => 'true_false',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'message' => 'Hide this on larger displays',
  			'default_value' => 0,
  			'ui' => 0,
  			'ui_on_text' => '',
  			'ui_off_text' => '',
  		),
  		array(
  			'key' => 'field_59f512984e501',
  			'label' => 'Mobile Hide',
  			'name' => 'mobile_hide',
  			'type' => 'true_false',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'message' => 'Hide this on mobile devices',
  			'default_value' => 0,
  			'ui' => 0,
  			'ui_on_text' => '',
  			'ui_off_text' => '',
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f4f2fcc0e59',
  	'title' => 'ExCon - Setting - Styling',
  	'fields' => array(
  		array(
  			'key' => 'field_59f4f31323e04',
  			'label' => 'Styling',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'left',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_59f4f7dad6db4',
  			'label' => 'Text',
  			'name' => 'text',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'block',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f4fb285375e',
  					'label' => 'Size',
  					'name' => 'size',
  					'type' => 'select',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '50',
  						'class' => '',
  						'id' => '',
  					),
  					'choices' => array(
  						'xsmall' => 'Extra Small',
  						'small' => 'Small',
  						'normal' => 'Normal',
  						'large' => 'Large',
  						'xlarge' => 'Extra Large',
  					),
  					'default_value' => array(
  						0 => 'normal',
  					),
  					'allow_null' => 0,
  					'multiple' => 0,
  					'ui' => 0,
  					'ajax' => 0,
  					'return_format' => 'value',
  					'placeholder' => '',
  				),
  				array(
  					'key' => 'field_59f4f7fcd6db5',
  					'label' => 'Text',
  					'name' => 'text',
  					'type' => 'clone',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'clone' => array(
  						0 => 'field_59f4f4c90fb26',
  					),
  					'display' => 'seamless',
  					'layout' => 'block',
  					'prefix_label' => 1,
  					'prefix_name' => 1,
  				),
  				array(
  					'key' => 'field_59f4fd2237175',
  					'label' => 'Link',
  					'name' => 'link',
  					'type' => 'clone',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'clone' => array(
  						0 => 'field_59f4f4c90fb26',
  					),
  					'display' => 'seamless',
  					'layout' => 'block',
  					'prefix_label' => 1,
  					'prefix_name' => 1,
  				),
  				array(
  					'key' => 'field_59f4fd4e37176',
  					'label' => 'Heading',
  					'name' => 'heading',
  					'type' => 'clone',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'clone' => array(
  						0 => 'field_59f4f4c90fb26',
  					),
  					'display' => 'seamless',
  					'layout' => 'block',
  					'prefix_label' => 1,
  					'prefix_name' => 1,
  				),
  			),
  		),
  		array(
  			'key' => 'field_59f4f44352e23',
  			'label' => 'Background',
  			'name' => 'background',
  			'type' => 'group',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layout' => 'block',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_59f4f47a52e24',
  					'label' => 'Image',
  					'name' => 'image',
  					'type' => 'image',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '100',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  					'preview_size' => 'large',
  					'library' => 'all',
  					'min_width' => '',
  					'min_height' => '',
  					'min_size' => '',
  					'max_width' => '',
  					'max_height' => '',
  					'max_size' => '',
  					'mime_types' => '',
  				),
  				array(
  					'key' => 'field_59f4f5378bf69',
  					'label' => 'Image Opacity',
  					'name' => 'image_opacity',
  					'type' => 'range',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '50',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => 100,
  					'min' => 1,
  					'max' => 100,
  					'step' => 1,
  					'prepend' => '',
  					'append' => '% opaque',
  				),
  				array(
  					'key' => 'field_59f4f55d8bf6a',
  					'label' => 'Color',
  					'name' => 'color',
  					'type' => 'clone',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'clone' => array(
  						0 => 'field_59f4f4c90fb26',
  					),
  					'display' => 'seamless',
  					'layout' => 'block',
  					'prefix_label' => 0,
  					'prefix_name' => 0,
  				),
  			),
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'normal',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => '',
  	'active' => 0,
  	'description' => '',
  ));

  acf_add_local_field_group(array(
  	'key' => 'group_59f4f11a8c805',
  	'title' => 'Exonym - Content Architect',
  	'fields' => array(
  		array(
  			'key' => 'field_59f518bce2c8a',
  			'label' => 'Content Architect',
  			'name' => 'content_architect',
  			'type' => 'flexible_content',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'layouts' => array(
  				'59f5252aa6116' => array(
  					'key' => '59f5252aa6116',
  					'name' => 'carousel',
  					'label' => 'Carousel',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f5252aa6117',
  							'label' => 'Carousel Content',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f78f9ac47f4',
  							'label' => 'Carousel Slides',
  							'name' => 'carousel_slides',
  							'type' => 'flexible_content',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'layouts' => array(
  								'59f78fa5d8a92' => array(
  									'key' => '59f78fa5d8a92',
  									'name' => 'custom_content',
  									'label' => 'Custom Content',
  									'display' => 'block',
  									'sub_fields' => array(
  										array(
  											'key' => 'field_59f7901c12b7a',
  											'label' => 'Content',
  											'name' => '',
  											'type' => 'tab',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'placement' => 'left',
  											'endpoint' => 0,
  										),
  										array(
  											'key' => 'field_59f78fb6c47f6',
  											'label' => 'Custom Content Area',
  											'name' => 'custom_content_area',
  											'type' => 'wysiwyg',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'default_value' => '',
  											'tabs' => 'all',
  											'toolbar' => 'full',
  											'media_upload' => 1,
  											'delay' => 1,
  										),
  										array(
  											'key' => 'field_59f7902f12b7b',
  											'label' => 'Settings',
  											'name' => 'settings',
  											'type' => 'clone',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'clone' => array(
  												0 => 'group_59f5076d561aa',
  												1 => 'group_59f4f2fcc0e59',
  											),
  											'display' => 'seamless',
  											'layout' => 'block',
  											'prefix_label' => 0,
  											'prefix_name' => 0,
  										),
  									),
  									'min' => '',
  									'max' => '',
  								),
  								'59f79741e1366' => array(
  									'key' => '59f79741e1366',
  									'name' => 'posts',
  									'label' => 'Posts',
  									'display' => 'block',
  									'sub_fields' => array(
  										array(
  											'key' => 'field_59f79741e1368',
  											'label' => 'Posts',
  											'name' => '',
  											'type' => 'tab',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'placement' => 'left',
  											'endpoint' => 0,
  										),
  										array(
  											'key' => 'field_59f797e2e136c',
  											'label' => 'Number of Blog Posts',
  											'name' => 'number_of_blog_posts',
  											'type' => 'number',
  											'instructions' => 'Use "-1" to show all posts',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'default_value' => 1,
  											'placeholder' => '',
  											'prepend' => '',
  											'append' => '',
  											'min' => -1,
  											'max' => '',
  											'step' => 1,
  										),
  										array(
  											'key' => 'field_59f79781e136a',
  											'label' => 'Settings',
  											'name' => 'settings',
  											'type' => 'clone',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'clone' => array(
  												0 => 'group_59f4f2fcc0e59',
  											),
  											'display' => 'seamless',
  											'layout' => 'block',
  											'prefix_label' => 0,
  											'prefix_name' => 0,
  										),
  									),
  									'min' => '',
  									'max' => '',
  								),
  								'59f80d702435f' => array(
  									'key' => '59f80d702435f',
  									'name' => 'testimonials',
  									'label' => 'Testimonials',
  									'display' => 'block',
  									'sub_fields' => array(
  										array(
  											'key' => 'field_59f80d7024360',
  											'label' => 'Testimonials',
  											'name' => '',
  											'type' => 'tab',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'placement' => 'left',
  											'endpoint' => 0,
  										),
  										array(
  											'key' => 'field_59f80d7024361',
  											'label' => 'Number of Testimonials',
  											'name' => 'number_of_testimonials',
  											'type' => 'number',
  											'instructions' => 'Use "-1" to show all testimonials',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'default_value' => 1,
  											'placeholder' => '',
  											'prepend' => '',
  											'append' => '',
  											'min' => -1,
  											'max' => '',
  											'step' => 1,
  										),
  										array(
  											'key' => 'field_59f80d7024362',
  											'label' => 'Settings',
  											'name' => 'settings',
  											'type' => 'clone',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'clone' => array(
  												0 => 'group_59f4f2fcc0e59',
  											),
  											'display' => 'seamless',
  											'layout' => 'block',
  											'prefix_label' => 0,
  											'prefix_name' => 0,
  										),
  									),
  									'min' => '',
  									'max' => '',
  								),
  							),
  							'button_label' => 'Add Slide',
  							'min' => '',
  							'max' => '',
  						),
  						array(
  							'key' => 'field_59f796b5e1364',
  							'label' => 'Carousel Options',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f793f783dc2',
  							'label' => 'Carousel Options',
  							'name' => 'carousel_options',
  							'type' => 'group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'layout' => 'block',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_59f78efec47f3',
  									'label' => 'Slides to Show',
  									'name' => 'slides_to_show',
  									'type' => 'range',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '33',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => 4,
  									'min' => 2,
  									'max' => 8,
  									'step' => 1,
  									'prepend' => '',
  									'append' => '',
  								),
  								array(
  									'key' => 'field_59f7942383dc3',
  									'label' => 'Show Arrows',
  									'name' => 'show_arrows',
  									'type' => 'true_false',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '34',
  										'class' => '',
  										'id' => '',
  									),
  									'message' => 'Show left/right arrows',
  									'default_value' => 1,
  									'ui' => 0,
  									'ui_on_text' => '',
  									'ui_off_text' => '',
  								),
  								array(
  									'key' => 'field_59f7945783dc4',
  									'label' => 'Autoplay',
  									'name' => 'autoplay',
  									'type' => 'true_false',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '33',
  										'class' => '',
  										'id' => '',
  									),
  									'message' => 'Automatically scroll through the slides',
  									'default_value' => 1,
  									'ui' => 0,
  									'ui_on_text' => '',
  									'ui_off_text' => '',
  								),
  							),
  						),
  						array(
  							'key' => 'field_59f5252aa6119',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'59f518c510eba' => array(
  					'key' => '59f518c510eba',
  					'name' => 'code',
  					'label' => 'Code',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f51932e2c8b',
  							'label' => 'Code',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f5193de2c8c',
  							'label' => 'Code Block',
  							'name' => 'code_block',
  							'type' => 'textarea',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'maxlength' => '',
  							'rows' => '',
  							'new_lines' => '',
  						),
  						array(
  							'key' => 'field_59f51958e2c8d',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'59f51e891dd74' => array(
  					'key' => '59f51e891dd74',
  					'name' => 'content',
  					'label' => 'Content',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f51e891dd75',
  							'label' => 'Content',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f52f356961f',
  							'label' => 'Content Area',
  							'name' => 'content_area',
  							'type' => 'wysiwyg',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'tabs' => 'all',
  							'toolbar' => 'full',
  							'media_upload' => 1,
  							'delay' => 1,
  						),
  						array(
  							'key' => 'field_59f51e891dd77',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'5a1d0d58d2fb4' => array(
  					'key' => '5a1d0d58d2fb4',
  					'name' => 'gallery',
  					'label' => 'Gallery',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5a1d0d69d2fb5',
  							'label' => 'Images',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_5a1d0d8fd2fb6',
  							'label' => 'Gallery Images',
  							'name' => 'gallery_images',
  							'type' => 'gallery',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'min' => '',
  							'max' => '',
  							'insert' => 'append',
  							'library' => 'all',
  							'min_width' => '',
  							'min_height' => '',
  							'min_size' => '',
  							'max_width' => '',
  							'max_height' => '',
  							'max_size' => '',
  							'mime_types' => '',
  						),
  						array(
  							'key' => 'field_5a1d0da4d2fb7',
  							'label' => 'Gallery Settings',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_5a1d1211d2fbc',
  							'label' => 'Gallery Display',
  							'name' => 'gallery_display',
  							'type' => 'button_group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'grid' => 'Grid',
  								'slideshow' => 'Slideshow',
  							),
  							'allow_null' => 0,
  							'default_value' => 'grid',
  							'layout' => 'horizontal',
  							'return_format' => 'value',
  						),
  						array(
  							'key' => 'field_5a1d116ad2fbb',
  							'label' => 'Image Size',
  							'name' => 'image_size',
  							'type' => 'select',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'choices' => array(
  								'thumbnail' => 'Thumbnail (Small)',
  								'thumbnail-medium' => 'Thumbnail (Medium)',
  								'thumbnail-large' => 'Thumbnail (Large)',
  								'small' => 'Small',
  								'medium' => 'Medium',
  								'large' => 'Large',
  							),
  							'default_value' => array(
  								0 => 'thumbnail-medium',
  							),
  							'allow_null' => 0,
  							'multiple' => 0,
  							'ui' => 0,
  							'ajax' => 0,
  							'return_format' => 'value',
  							'placeholder' => '',
  						),
  						array(
  							'key' => 'field_5a1d13517f731',
  							'label' => 'Image Grid',
  							'name' => 'image_grid',
  							'type' => 'group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5a1d1211d2fbc',
  										'operator' => '==',
  										'value' => 'grid',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'layout' => 'table',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_5a1d13a37f732',
  									'label' => 'Row Count',
  									'name' => 'row_count',
  									'type' => 'number',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => 5,
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => 'images per row',
  									'min' => 1,
  									'max' => '',
  									'step' => '',
  								),
  								array(
  									'key' => 'field_5a1d13ee7f733',
  									'label' => 'Padding',
  									'name' => 'padding',
  									'type' => 'number',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => 10,
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => 'px per image',
  									'min' => 0,
  									'max' => '',
  									'step' => '',
  								),
  								array(
  									'key' => 'field_5a1d14497f734',
  									'label' => 'Alignment',
  									'name' => 'alignment',
  									'type' => 'group',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'layout' => 'row',
  									'sub_fields' => array(
  										array(
  											'key' => 'field_5a1d14c57f735',
  											'label' => 'X',
  											'name' => 'x',
  											'type' => 'select',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'choices' => array(
  												'between' => 'Space Between',
  												'around' => 'Space Around',
  												'center' => 'Center',
  												'start' => 'Start',
  												'end' => 'End',
  											),
  											'default_value' => array(
  												0 => 'between',
  											),
  											'allow_null' => 0,
  											'multiple' => 0,
  											'ui' => 0,
  											'ajax' => 0,
  											'return_format' => 'value',
  											'placeholder' => '',
  										),
  										array(
  											'key' => 'field_5a1d15317f736',
  											'label' => 'Y',
  											'name' => 'y',
  											'type' => 'select',
  											'instructions' => '',
  											'required' => 0,
  											'conditional_logic' => 0,
  											'wrapper' => array(
  												'width' => '',
  												'class' => '',
  												'id' => '',
  											),
  											'choices' => array(
  												'top' => 'Top',
  												'center' => 'Center',
  												'bottom' => 'Bottom',
  											),
  											'default_value' => array(
  												0 => 'center',
  											),
  											'allow_null' => 0,
  											'multiple' => 0,
  											'ui' => 0,
  											'ajax' => 0,
  											'return_format' => 'value',
  											'placeholder' => '',
  										),
  									),
  								),
  							),
  						),
  						array(
  							'key' => 'field_5a1d1664d709c',
  							'label' => 'Image Slideshow',
  							'name' => 'image_slideshow',
  							'type' => 'group',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => array(
  								array(
  									array(
  										'field' => 'field_5a1d1211d2fbc',
  										'operator' => '==',
  										'value' => 'slideshow',
  									),
  								),
  							),
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'layout' => 'table',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_5a1d17cbd709d',
  									'label' => 'Auto',
  									'name' => 'auto',
  									'type' => 'true_false',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'message' => 'Autoplay slideshow',
  									'default_value' => 0,
  									'ui' => 0,
  									'ui_on_text' => '',
  									'ui_off_text' => '',
  								),
  								array(
  									'key' => 'field_5a1d17ded709e',
  									'label' => 'Autoplay Speed',
  									'name' => 'autoplay_speed',
  									'type' => 'number',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => array(
  										array(
  											array(
  												'field' => 'field_5a1d17cbd709d',
  												'operator' => '==',
  												'value' => '1',
  											),
  										),
  									),
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => 5,
  									'placeholder' => '',
  									'prepend' => '',
  									'append' => 'seconds',
  									'min' => 0,
  									'max' => '',
  									'step' => '',
  								),
  								array(
  									'key' => 'field_5a1d1809d709f',
  									'label' => 'Dots',
  									'name' => 'dots',
  									'type' => 'true_false',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'message' => 'Show slide navigation dots',
  									'default_value' => 0,
  									'ui' => 0,
  									'ui_on_text' => '',
  									'ui_off_text' => '',
  								),
  								array(
  									'key' => 'field_5a1d183fd70a0',
  									'label' => 'Arrows',
  									'name' => 'arrows',
  									'type' => 'true_false',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'message' => 'Show slide navigation arrows',
  									'default_value' => 0,
  									'ui' => 0,
  									'ui_on_text' => '',
  									'ui_off_text' => '',
  								),
  							),
  						),
  						array(
  							'key' => 'field_5a1d159c7f737',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'59f68188e809a' => array(
  					'key' => '59f68188e809a',
  					'name' => 'multi-column',
  					'label' => 'Multi-Column',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f68188e809b',
  							'label' => 'Column Headings',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f681a0e809e',
  							'label' => 'Heading',
  							'name' => 'heading',
  							'type' => 'textarea',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'maxlength' => '',
  							'rows' => '',
  							'new_lines' => '',
  						),
  						array(
  							'key' => 'field_59f6822de809f',
  							'label' => 'Heading Border',
  							'name' => 'heading_border',
  							'type' => 'true_false',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'message' => 'Show border beneath the heading',
  							'default_value' => 0,
  							'ui' => 0,
  							'ui_on_text' => '',
  							'ui_off_text' => '',
  						),
  						array(
  							'key' => 'field_59f68276e80a0',
  							'label' => 'Sub-Heading',
  							'name' => 'sub-heading',
  							'type' => 'textarea',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => '',
  							'placeholder' => '',
  							'maxlength' => '',
  							'rows' => '',
  							'new_lines' => '',
  						),
  						array(
  							'key' => 'field_59f68291e80a1',
  							'label' => 'Sub-Heading Border',
  							'name' => 'sub-heading_border',
  							'type' => 'true_false',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'message' => 'Show a border beneath the sub heading',
  							'default_value' => 0,
  							'ui' => 0,
  							'ui_on_text' => '',
  							'ui_off_text' => '',
  						),
  						array(
  							'key' => 'field_59f68327e80a4',
  							'label' => 'Columns',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'top',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f682d1e80a2',
  							'label' => 'Columns',
  							'name' => 'columns',
  							'type' => 'repeater',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'collapsed' => '',
  							'min' => 0,
  							'max' => 0,
  							'layout' => 'row',
  							'button_label' => 'Add Column',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_59f682fde80a3',
  									'label' => 'Column',
  									'name' => 'column',
  									'type' => 'wysiwyg',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'tabs' => 'all',
  									'toolbar' => 'full',
  									'media_upload' => 1,
  									'delay' => 1,
  								),
  							),
  						),
  						array(
  							'key' => 'field_59f68355e80a5',
  							'label' => 'Column Settings',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'top',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f68407e80a6',
  							'label' => 'Column Width',
  							'name' => 'column_width',
  							'type' => 'range',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'default_value' => 50,
  							'min' => 10,
  							'max' => 100,
  							'step' => 10,
  							'prepend' => '',
  							'append' => '',
  						),
  						array(
  							'key' => 'field_59f68459e80a7',
  							'label' => 'Column Inner',
  							'name' => 'column_inner',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'field_59f4fea38a9a2',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 1,
  							'prefix_name' => 1,
  						),
  						array(
  							'key' => 'field_59f68188e809d',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'59f51add98f72' => array(
  					'key' => '59f51add98f72',
  					'name' => 'slideshow',
  					'label' => 'Slideshow',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_59f51add98f73',
  							'label' => 'Slides',
  							'name' => '',
  							'type' => 'tab',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'placement' => 'left',
  							'endpoint' => 0,
  						),
  						array(
  							'key' => 'field_59f51b0e98f76',
  							'label' => 'Slides',
  							'name' => 'slides',
  							'type' => 'repeater',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'collapsed' => '',
  							'min' => 1,
  							'max' => 0,
  							'layout' => 'block',
  							'button_label' => 'Add Slide',
  							'sub_fields' => array(
  								array(
  									'key' => 'field_59f51dfde5c85',
  									'label' => 'Slide Content',
  									'name' => '',
  									'type' => 'tab',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'placement' => 'left',
  									'endpoint' => 0,
  								),
  								array(
  									'key' => 'field_59f51d9f98f7b',
  									'label' => 'Slide Content',
  									'name' => 'slide_content',
  									'type' => 'wysiwyg',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'default_value' => '',
  									'tabs' => 'all',
  									'toolbar' => 'full',
  									'media_upload' => 1,
  									'delay' => 1,
  								),
  								array(
  									'key' => 'field_59f51df7e5c84',
  									'label' => 'Settings',
  									'name' => 'settings',
  									'type' => 'clone',
  									'instructions' => '',
  									'required' => 0,
  									'conditional_logic' => 0,
  									'wrapper' => array(
  										'width' => '',
  										'class' => '',
  										'id' => '',
  									),
  									'clone' => array(
  										0 => 'group_59f5140d56a78',
  									),
  									'display' => 'seamless',
  									'layout' => 'block',
  									'prefix_label' => 0,
  									'prefix_name' => 0,
  								),
  							),
  						),
  						array(
  							'key' => 'field_59f51add98f75',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f4fc19d26a0',
  								1 => 'group_59f51288a86d9',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  				'59f8f5d332e65' => array(
  					'key' => '59f8f5d332e65',
  					'name' => 'staff',
  					'label' => 'Staff',
  					'display' => 'block',
  					'sub_fields' => array(
  						array(
  							'key' => 'field_5a20ce76591db',
  							'label' => 'Staff Plugin Settings',
  							'name' => 'staff_plugin_settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_5a1f84b391c69',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  						array(
  							'key' => 'field_59f8f5d332e68',
  							'label' => 'Settings',
  							'name' => 'settings',
  							'type' => 'clone',
  							'instructions' => '',
  							'required' => 0,
  							'conditional_logic' => 0,
  							'wrapper' => array(
  								'width' => '',
  								'class' => '',
  								'id' => '',
  							),
  							'clone' => array(
  								0 => 'group_59f5140d56a78',
  							),
  							'display' => 'seamless',
  							'layout' => 'block',
  							'prefix_label' => 0,
  							'prefix_name' => 0,
  						),
  					),
  					'min' => '',
  					'max' => '',
  				),
  			),
  			'button_label' => 'Add Content',
  			'min' => '',
  			'max' => '',
  		),
  	),
  	'location' => array(
  		array(
  			array(
  				'param' => 'post_type',
  				'operator' => '==',
  				'value' => 'page',
  			),
  		),
  	),
  	'menu_order' => 0,
  	'position' => 'acf_after_title',
  	'style' => 'seamless',
  	'label_placement' => 'top',
  	'instruction_placement' => 'label',
  	'hide_on_screen' => array(
  		0 => 'the_content',
  		1 => 'excerpt',
  		2 => 'custom_fields',
  		3 => 'discussion',
  		4 => 'comments',
  		5 => 'revisions',
  		6 => 'slug',
  		7 => 'author',
  		8 => 'format',
  		9 => 'featured_image',
  		10 => 'categories',
  		11 => 'tags',
  		12 => 'send-trackbacks',
  	),
  	'active' => 1,
  	'description' => '',
  ));

  endif;
